services:
  etcd:
    image: public.ecr.aws/bitnami/etcd:3.5
    container_name: etcd-server
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379

  pg-node1: &pg_config
    image: registry.opensource.zalan.do/acid/spilo-14:2.1-p6
    container_name: pg-node1
    environment:
      # On passe TOUTE la config en une seule ligne JSON propre
      - PATRONI_CONFIGURATION={"etcd3":{"hosts":["etcd-server:2379"]},"scope":"ecommerce","name":"node1","postgresql":{"listen":"0.0.0.0:5432","connect_address":"pg-node1:5432"}}
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replpass
    depends_on:
      - etcd

  pg-node2:
    <<: *pg_config
    container_name: pg-node2
    environment:
      - PATRONI_CONFIGURATION={"etcd3":{"hosts":["etcd-server:2379"]},"scope":"ecommerce","name":"node2","postgresql":{"listen":"0.0.0.0:5432","connect_address":"pg-node2:5432"}}
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replpass

  pg-node3:
    <<: *pg_config
    container_name: pg-node3
    environment:
      - PATRONI_CONFIGURATION={"etcd3":{"hosts":["etcd-server:2379"]},"scope":"ecommerce","name":"node3","postgresql":{"listen":"0.0.0.0:5432","connect_address":"pg-node3:5432"}}
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replpass

  haproxy:
    image: public.ecr.aws/docker/library/haproxy:2.4-alpine
    container_name: haproxy
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - pg-node1
      - pg-node2
      - pg-node3